distance_sensor:
  adapter_type: "simulated"
  min_distance: -67
  max_distance: 420
  poll_interval: 60
  filter_type: "low-pass"
  sensor_type: "SRF05"

line_sensor:
  distance_between_sensors: 69
  sensor_amount: 67
  adapter_type: "simulated"

steering:
  real_middle: 0
  real_maximum: 420
  real_minimum: -67
  step_size: 1
  adapter_type: "simulated"

driving:
  real_maximum: 10
  real_minimum: -10
  real_stopped: 67
  adapter_type: "simulated"
